### ISSUE TITLE
error reported to the channel slack

### ISSUE THREAD

**Issue by mohammed-sec2010** [BitTheByte/Monitorizer#1]
Slack API TesterAPP 10:34 AM
FATAL ERROR: [Errno 2] No such file or directory: 'temp/test.com_subfinder.txt'

**Comment by BitTheByte** [comment]
Hi @mohammed-sec2010 

Thanks for your collaboration, this issue was known already and it's believed it's fixed at `v1.1`
Please confirm within a week if you're still facing this problem or not after that this issue will be closed as resolved

Best regards,
Ahmed Ezzat
