### ISSUE TITLE
[Feature Request] Add Httpx to thirdparties 

### ISSUE THREAD

**Issue by A0x01** [BitTheByte/Monitorizer#10]
Hi , Please can you add httpx with it options like [title, status-code, web-server -cname]
thanks in advance for this awesome tool

**Comment by BitTheByte** [comment]
Hey @A0x01 

I'm happy to do so, if possible please provide some screenshots on how you imagine this will be implemented

Thanks

**Comment by A0x01** [comment]
cat subdomin_list.txt | httpx -title -status-code -content-type -web-server -cname

**Comment by BitTheByte** [comment]
Hi @A0x01 

Thanks for your reply. this could be implemented using python libraries with no need to use httpx. I will reformat slack message to look like this

| Domain |Title | Status Code | Web Server | Alternative names |  Ports |
| --------- | ---- | ------------- | -------------|----------------------| ----- |
| host.com| Host.com Login | 200 OK | ngnix  | example-node-1.host.com | 80,443
| example.com| File not found | 404 Not Found | apache  | - | 80,443,8080

Also, I decided not to include content type with the message as most of the targets will return `application/json` or `text/html` and both of them not really that useful to report 

This feature will be available in the next release, Thanks for your collaboration.

**Comment by A0x01** [comment]
this will be more useful 
Thanks alot for your efforts

**Comment by BitTheByte** [comment]
Hello @A0x01 

Unfortunately, this has been delayed to `v2.6` as integrating nuclei was more critical. 
`v2.5` just entered the open beta and publicly accessible at the dev branch at https://github.com/BitTheByte/Monitorizer/tree/dev

**Comment by A0x01** [comment]
thanks

**Comment by BitTheByte** [comment]
Monitoring will only focus on subdomain monitoring. More integrations will be coming soon to integrate with my other tools.
