### ISSUE TITLE
Is this project still maintained ?

### ISSUE THREAD

**Issue by s2b1n0** [BitTheByte/Monitorizer#14]
Hey.

As the last commit was on July 2021, I wanted to reach out to know if there is interesting on keeping this project updated, or any plans for the future. Thanks a lot.

**Comment by BitTheByte** [comment]
Hi @s2b1n0 

The current codebase is unmaintained as I wanted to have a more unified interface for my tools thus the functionality of this tool will be included in another project coming soon

**Comment by s2b1n0** [comment]
Hey @BitTheByte , thanks for your quick answer.

That's nice. I'm excited to see the new release. 🙂
