### ISSUE TITLE
could you make a full install details?

### ISSUE THREAD

**Issue by blackcodersec** [BitTheByte/Monitorizer#19]
could you make a full install details?
your docker cmd not working.

**Comment by BitTheByte** [comment]
Hey @blackcodersec

Please describe the problem you're facing. E.g. errors, tracelogs ... etc, detailed installation steps are not possible as I'm still changing the deployment strategy

**Comment by blackcodersec** [comment]
![image](https://github.com/BitTheByte/Monitorizer/assets/72689232/f05c30cc-1c4a-4a3c-97e7-9e07a70dc2b1)

**Comment by blackcodersec** [comment]
and please write full installation guide

**Comment by BitTheByte** [comment]
Should be working now. Could you please confirm?

**Comment by blackcodersec** [comment]
it is now working.
