### ISSUE TITLE
[Improvement] Amass & Slack 

### ISSUE THREAD

**Issue by JoshuaMart** [BitTheByte/Monitorizer#2]
Hi,
First of all, thanks for your tool, it's really cool but I think it could be even better, including adding a newer version of Amass and allowing users to add their API keys to the Amass configuration file because some APIs are not present in particular SecurityTrails which is an excellent source of domain.

I did a test on my side by modifying the current binary by the 3.5.1 version, I adding the file `amass.ini` to the config folder and I changed the amass line in `default.json` to : 
```
"amass":{
                "cmd": "./ext/amass/amass enum -active -brute -min-for-recursive 1 -d {target} -config {amass_config} -o {output} -w {alts_wordlist}",
                "formats":{
                        "wordlist":"wordlists/namelist.txt",
                        "alts_wordlist":"wordlists/alterations.txt",
                        "amass_config":"config/amass.ini"
                }
        },
``` 
It is therefore also necessary to add the Amass config file and update the Readme to specify that it is more interesting to modify the amass config file with its API keys.

And by modifying the token requested for slack by the new version (this version will be outdated on May 5th)

If it's okay with you, I can handle doing PR for the Amass part.

Regards,
Jomar

**Comment by BitTheByte** [comment]
Hello @JoshuaMart 

I'm really happy that you're interested in improving this project. Feel free to start working on the PR and we will discuss the new improvements when completed

Thanks
