### ISSUE TITLE
Traceback errro

### ISSUE THREAD

**Issue by ipk1** [BitTheByte/Monitorizer#5]
Hi, when i run the command the following error is displayed 

Traceback (most recent call last):
  File "monitor.py", line 5, in <module>
    from events.on import Events
  File "/root/Monitorizer/events/on.py", line 3, in <module>
    from core.report import Report
  File "/root/Monitorizer/core/report.py", line 2, in <module>
    from .acunetix import Acunetix
  File "/root/Monitorizer/core/acunetix.py", line 64
    raise AXException("JSON_PARSING_ERROR", f"Json Parsing has occured: {e}")

thanks

**Comment by BitTheByte** [comment]
Hello @ipk1 

Thanks for contacting me. kindly answer the following to ensure that I can help you in the best way possible 
* OS 
* Python Version
* Did you download the tool from GitHub or did a `git pull/clone`?
* The command-line used to run the tool
* Acunetix version (if available)

**Comment by ipk1** [comment]
OS: linux 64bit debian
python 3.5
i did a git clone
python3 monitor.py -w d.txt

acunetix 13v

thanks

**Comment by ipk1** [comment]
hi, so meanwhile what i did was removed f" and replaced it with " and i get the following error
Traceback (most recent call last):
  File "monitor.py", line 42, in <module>
    events.start()
  File "/root/Monitorizer/events/on.py", line 41, in start
    self.slack("Monitorizer framework v{ver} started :tada:".format(ver=metadata["version"]["monitorizer"]))
  File "/root/Monitorizer/core/report.py", line 28, in slack
    client = slack.WebClient(self.slack_token)
AttributeError: module 'slack' has no attribute 'WebClient'

slack version:
slack (0.0.2)
slackclient (1.3.2)

thanks

**Comment by BitTheByte** [comment]
Could you please upgrade to python 3.8 or 3.7 and try again? let me know if that works

**Comment by ipk1** [comment]
oh boy, sorry missed it, my bad , will check and update, thanks mate

**Comment by BitTheByte** [comment]
Happy to help 😄

**Comment by ipk1** [comment]
hi, i am able run it now but i am facing with these issues, [10/08/2020 01:21:15] | ERR | Unable to execute aiodnsbrute make sure to install all requirements
 [10/08/2020 01:21:15] | SCC | Started events server at http://0.0.0.0:6500/slack
 [10/08/2020 01:21:15] | ERR | The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'invalid_auth'}

python3.7

thanks

**Comment by ipk1** [comment]
nvm, figured out the slack thing however, aiodnsbrute refuses to run,

thanks
ipk1
