### ISSUE TITLE
slack api adding problem

### ISSUE THREAD

**Issue by OviKing123** [BitTheByte/Monitorizer#6]
sir,
can you please add more details how to add slack api ?

**Comment by OviKing123** [comment]
sir,
can you please add more details how to add slack api ?

**Comment by BitTheByte** [comment]
Hello @OviKing123,

Sorry for deleting your comment (it's duplicate from the original issue description). I'm planning to write full documentation for how to integrate this tool with slack

**Comment by OviKing123** [comment]
thank a lot bro for your reply

**Comment by BitTheByte** [comment]
Hi @OviKing123 

This issue is fixed on the `dev` branch https://github.com/BitTheByte/Monitorizer/blob/dev/docs/get_started.md. this will be closed soon.

Thanks for your collaboration :)
