### ISSUE TITLE
bot command doesnt add other tlds

### ISSUE THREAD

**Issue by ipk1** [BitTheByte/Monitorizer#7]
Hi,

when i try to add a domina to the watch list , the add command doesn't add tld's with cl, ie anydomain.cl doenst add.

thanks

**Comment by BitTheByte** [comment]
Thanks for contacting me, I'll take a look into it

**Comment by BitTheByte** [comment]
I'm unable to verify this. could you please provide information on how how you were able to produce this? 

![image](https://user-images.githubusercontent.com/16452985/90964546-d0230b00-e4c1-11ea-9adb-feef73128687.png)

**Comment by ipk1** [comment]
Hi,

This happens when the domain name is large.

Thanks

**Comment by BitTheByte** [comment]
I am still not able to reproduce that even with a long domain name. could you please provide the name you're testing with?

**Comment by BitTheByte** [comment]
Hello @ipk1

I'll close this for now as it appears to be a weird edge-case. feel free to contact me if the problem still exists and I'll take another look into it

Thanks
